//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urunler_Dbfirst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASILAR_TESTEntities2 : DbContext
    {
        public ASILAR_TESTEntities2()
            : base("name=ASILAR_TESTEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_DOZ> TBL_DOZ { get; set; }
        public virtual DbSet<TBL_STOK> TBL_STOK { get; set; }
        public virtual DbSet<TBL_TASIMA> TBL_TASIMA { get; set; }
        public virtual DbSet<TBL_URUN> TBL_URUN { get; set; }
    }
}
