//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urunler_Dbfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DOZ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DOZ()
        {
            this.TBL_TASIMA = new HashSet<TBL_TASIMA>();
        }
    
        public int D_ID { get; set; }
        public Nullable<int> DOZ_ADI { get; set; }
        public string MIKTAR { get; set; }
        public Nullable<System.DateTime> MIAT { get; set; }
    
        public virtual TBL_STOK TBL_STOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TASIMA> TBL_TASIMA { get; set; }
    }
}
