//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urunler_Dbfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_URUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_URUN()
        {
            this.TBL_STOK = new HashSet<TBL_STOK>();
        }
    
        public int ID { get; set; }
        public string URUN_AD { get; set; }
        public string URUN_TUR { get; set; }
        public string UYGULAMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK> TBL_STOK { get; set; }
    }
}
