//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urunler_Dbfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TASIMA
    {
        public int T_ID { get; set; }
        public Nullable<int> U_TASIMA { get; set; }
        public string TASIMA_TIPI { get; set; }
    
        public virtual TBL_DOZ TBL_DOZ { get; set; }
    }
}
